api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity'] # Chemin sur lequel api_platform agit 
    collection:
        pagination:
            enabled: false # On désactive la pagination de api_platform
            items_per_page: 5 # Nombre d'items par page pour la pagination
            client_enabled: true # Permet de donner l'autorisation d'envoyer dans la requête un paramètre pour activer ou non la pagination
            client_items_per_page: true # le nombre d'items par page de la pagination peut être modifié via un paramètre dans la requête (param: ?itemsPerPage=20)
            items_per_page_parameter_name: "count" # On renomme le nom du param de requête des items par page à "count" (par défaut c'est itemsPerPage)

